######################################################################
# Automatically generated by qmake (1.07a) Thu Feb 10 21:15:48 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += fabien.h fenetre.h imgbox.h mat.h romain.h sami.h
SOURCES += fabien.cpp \
           fenetre.cpp \
           imgbox.cpp \
           main.cpp \
           mat.cpp \
           romain.cpp \
           sami.cpp
